# Generated by Django 4.1.4 on 2022-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=100)),
                ('choice', models.CharField(blank=True, default='', max_length=20)),
                ('answer', models.BooleanField(default=False)),
            ],
        ),
    ]
