# Generated by Django 4.1.4 on 2022-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_quiz_api_delete_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz_api',
            options={},
        ),
        migrations.RemoveField(
            model_name='quiz_api',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz_api',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='quiz_api',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quiz_api',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz_api',
            name='data',
            field=models.JSONField(default='{}'),
        ),
    ]
