# Generated by Django 4.1.4 on 2022-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_quiz_api_options_remove_quiz_api_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_api',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
