# Generated by Django 4.1.4 on 2022-12-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_quiz_api_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_api',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
