# Generated by Django 4.1.4 on 2022-12-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_quiz_api_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_api',
            old_name='data',
            new_name='answers',
        ),
        migrations.AddField(
            model_name='quiz_api',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz_api',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
